<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>
<?php
	$_postCollection = $block->getPostCollection();
?>

<div class="recent-posts">
<?php if ($_postCollection->count()): ?>
    <div class="owl-carousel row">
		    <?php foreach ($_postCollection as $_post): ?>
					<div class="item card">
						<div class="card-header">
							<?php if($post_image = $_post->getFeaturedImage()): ?>
								<img class="card-img-top" src="<?php echo $post_image; ?>" alt=""/>
							<?php endif; ?>
						</div>
						<div class="card-body">
							<h1 class="card-title">
								<a href="<?php echo $_post->getPostUrl() ?>" >
									<?php echo $block->escapeHtml($_post->getTitle()) ?>
								</a>
							</h1>
  					</div>
					</div>

		    <?php endforeach; ?>
	</div>
<?php endif ?>
</div>
<script type="text/javascript">
        require([
            'jquery',
            'owl.carousel/owl.carousel.min'
        ], function ($) {
    
            $("#latest_news .owl-carousel").owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                navText: ["<em class='porto-icon-chevron-left'></em>","<em class='porto-icon-chevron-right'></em>"],
                dots: false,
                responsive: {
                    0: {
                        items:1
                    },
                    640: {
                        items:2
                    },
                    768: {
                        items:2
                    },
                    992: {
                        items:3
                    },
                    1200: {
                        items:3
                    }
                }
            });
			
			$('#latest_news .active').first().addClass('first_blog_post');
			
			var owl = $('.owl-carousel.row');
			
			owl.owlCarousel();
			
			owl.on('translated.owl.carousel changed.owl.carousel', function(event) {
			
				if (!$('#latest_news .owl-item').hasClass('first_blog_post') && $('#latest_news .owl-item').hasClass('active')) {
					
					$('#latest_news .owl-item').removeClass('first_blog_post');
					$('#latest_news .active').first().addClass('first_blog_post');
		
				}else{
		
					$('#latest_news .owl-item').removeClass('first_blog_post');
		
				}
			});
        
        });
    </script>
