<?php

use Magento\Framework\App\Action\Action;

$enable = $block->getEnableConfig();
if(!$enable) {}
else {
    $_productCollection = $block->createCollection();
    // var_dump($_productCollection ); die;
    $key = $block->genKey();
    $title = $block->getWidgetName();
 if (!$_productCollection->count()): ?>

    <?php else: ?>
        <div class="container">
            <div class="row">
               <div class="col-6">
                    <h1 class="background"><span><?= __('Best Sellers') ?></span></h1>
               </div>
               <div class="col-6">
                   <div>
                       <button>All time</button>
                       <button>Last Year</button>
                       <button>Last Month</button>
                   </div>
               </div> 
            </div>
        </div>


        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>



        <div class="block widget block-viewed-products">
            <div class="block-content">
                <div class="products wrapper <?= $block->escapeQuote($viewMode) ?> products-<?= $block->escapeQuote($viewMode) ?>">
                    <?php $iterator = 1;?>
                    <ol class="products list items product-items bss-slick-slider<?= $block->escapeQuote($key) ?>">

                        <?php foreach ($_productCollection as $_product): ?>
                            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php

                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml()?>
                                </a>
                            </div>
                            <?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>


                    </ol>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php
}
?>
