<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<div class="layered-nav">
    <label for="filtro"> <?= __(" FILTRO SIPAS") ?> </label>
    <select id="filtro">
        <?php foreach ($filterItems as $filterItem) : ?>


            <?php if ($filterItem->getCount() > 0) : ?>
                <?php
                $blockPagination = $block->getLayout()->createBlock('Magento\Theme\Block\Html\Pager');


                $query = [
                    $filterItem->getFilter()->getRequestVar() => $filterItem->getValue(),
                    // exclude current page from urls
                    $blockPagination->getPageVarName() => null,
                ];

                ?>
                <option class="item" value="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $query]); ?>">

                    <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $query]); ?>">
                        <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    </a>
                </option>
            <?php else : ?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
            <?php endif; ?>
        <?php endforeach ?>
        <select>
</div>


<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $("#filtro").on('change', function() {
            var url = $('#filtro').find(":selected").val();
            window.location.href = url;
        });
    });
</script>
