<?php 
	
	$om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->get('\Magento\Store\Model\StoreManagerInterface');
	$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); 


	$_product = $block->getProduct();
	

	$title = $_product->getName();
	$price = $_product->getPrice();
	$image = $_product->getImage();
	$catalog = 'catalog/product';	
	$image = $mediaUrl . $catalog .  $_product->getImage();
	$qty = 1;
	$total = $price * $qty;
	$items = 1;


?>

<style type="text/css">

#add-to-cart-modal {
  font-size: 20px;
}
#add-to-cart-modal  b{
  color: #dd1f40;
}
</style>

<div id="add-to-cart-modal" class="container" style="display: none;">
   <div class="row">
   		<div class="col-6">
   			<div class="row">
   				<div class="col-6">
   					<img class="img-fluid" src="<?= $image ?>"> 
   				</div>
   				<div class="col-6 details">
   					<span><b>Titulli: </b> <?= $title ?></span><br>
   					<span><b>Sasia:</b> <?= $qty ?></span><br>
   					<span><b>Totali: </b> <?= $total ?> </span><br>
   				</div>
   			</div>
   		</div>
   		<div class="col-6 cart">
   			<p>
   				<b class="libra"></b>
   				Libra ndodhen ne shporten tuaj
   			</p>
   			<span>Totali: <b class="price"></b></span>
   		</div>
   </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '<?= __("Libri u shtua me sukses ne shporten tuaj") ?>',
                buttons: [
	                {
	                    text: $.mage.__('Vazhdo me blerjen'),
	                    class: '',
	                    click: function () {
	                        this.closeModal();
	                    }
	                },
	                {
						text: $.mage.__('Perfundo Porosine'),
	                    class: '',
	                    click: function () {
	                        window.location.href = "<?= $block->getUrl('checkout', ['_secure' => true]) ?>";
	                    }
	                }
                ]
            };
            var popup = modal(options, $('#add-to-cart-modal'));
            $("#product-addtocart-button").on("click",function(){
              var items = $('#minicart-content-wrapper .items-total .count').text();
              var price = $('#minicart-content-wrapper .subtotal .price').text();
              var qty   = $('#qty').val();
              $('#add-to-cart-modal .libra').empty().append(parseInt(items) + parseInt(qty));
              $('#add-to-cart-modal .price').empty().append(price);
             
                $('#add-to-cart-modal').modal('openModal');
            });
        }
    );
</script>