<?php $media  = $this->getMediaUrl() . 'sub/'; ?>
<?php

$cat = $this->getCategories()
	->getItemById(14);

$childrens = $cat->getChildrenCategories()
	->toArray();
?>
<div class="container sub">
	<div id="subcategories">
		<?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('libra_subcategories')->toHtml(); ?>

	</div>
</div>
<style type="text/css">
	.hovered_img {
		display: none;
	}
</style>

<script type="text/javascript">
	require(['jquery'], function($) {

		var subcategories = $('#subcategories');

		$(document).mouseup(function(e) {
			var container = $("#subcategories");
			// if the target of the click isn't the container nor a descendant of the container
			console.log($(e.target));
			console.log($(e.target).hasClass("level-top"));
			if (!container.is(e.target) && container.is(":visible") && container.has(e.target).length === 0 && $(e.target).hasClass("level-top") == false && $(e.target).parent().hasClass('level-top') == false) {
				container.slideToggle();
			}

		});


		$('#libra-menu').click(function(e) {
			e.preventDefault();
			subcategories.slideToggle();

			if ($('html').hasClass("nav-open")) {
				$('html').removeClass("nav-open")
				$('html').removeClass("nav-before-open")
			}
		});

	});
</script>