<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php 
$url= $block->getUrl('blog');
$name="Blog";
$img= $this->getViewFileUrl('images/blog_banner.jpg');
?>
<div class="blog-banner-image">
<img src='<?php echo $img; ?>' alt="">
    <div class="blog_share_bg">
        <p>share</p>
        <ul>
            <li>
                <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($url);?>" 
                   onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' 
                   title="Share on FaceBook">
                    <em class="porto-icon-facebook">&nbsp;</em>
                </a>
            </li>

            <li>
                <a href="https://www.instagram.com/aeditions_albania/?hl=en" 
                   onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false'>
                    <em class="porto-icon-instagram">&nbsp;</em>
                </a>
            </li>

            <li>
                <a href="http://twitter.com/home/?status=<?php echo urlencode($url);?>" 
                   onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false'  
                   title="Share on Twitter">
                    <em class="porto-icon-twitter">&nbsp;</em>
                </a>
            </li>

            <li>
                <a href="https://www.pinterest.com/pin/create/button/?url=<?php echo urlencode($url);?>&media=<?php echo urlencode($img) ?>         &description=<?php echo urlencode($name)?>" 
                   onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false'>
                   <em class="porto-icon-pinterest">&nbsp;</em>
               </a>
            </li>
        </ul>

    </div>
</div>


<?php
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>

    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper">
        <?php $iterator = 1; ?>
        <div class="container">
            <?php foreach ($_postCollection as $_post): ?>
                <?php echo $block->getPostHtml($_post) ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $block->getToolbarHtml() ?>

    <script type="text/javascript">var addthis_config = {"data_track_clickback":false};</script>
    <script type="text/javascript" async src="//s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4def63cd3cf37569"></script>
    <script type="text/javascript">
        var addthis_config = {
            ui_language: "en"
        }
    </script>
<?php endif; ?>
