<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
?>

<div class="container">
        
        <div id="post" class="row">
            
            <div class="col-xl-4 col-lg-4 col-md-12 post_image">
               
                <div class="image_part">
                     <?php if($post_image = $_post->getFeaturedImage()): ?>
                        <img src="<?php echo $post_image; ?>" alt=""/>
                     <?php endif; ?>
                </div>
            
            </div>

            <div class="col-xl-8 col-lg-8 col-md-12 post_content">
                
                <div class="col-xl-12">
                    <h1 class="title">
                          <?= $_postName; ?>
                    </h1>
                </div>
                <div  class="col-xl-12 content">
                    
                    <?php echo $block->getContent() ?>
                </div>
            </div>

        </div>
    
 </div>
