<h1><?= __('Contact Us') ?></h1>


<h2>Keni ndonjë pyetje?</h2>

<p>
  Shiko faqen <a href="#"> “Pyetje të shpeshta” </a>
  për të parë nëse përgjigjja është aty.
  Në qoftë se jo, ju lutemi të kontaktoni
  shërbimin ndaj klientit. Faleminderit!
</p>

<p>Tel: <a tel="+355 69 20 33 200">+355 69 20 33 200</a> </p>

<div class="social-buttons">
	
	<a title="Share on FaceBook">
		<em class="porto-icon-facebook">&nbsp;</em>
	</a>
	
	<a>
		<em class="porto-icon-instagram">&nbsp;</em>
	</a>
	
	<a>
		<em class="porto-icon-linkedin-squared">&nbsp;</em>
	</a>
	
	<a>
		<em class="porto-icon-pinterest">&nbsp;</em>
	</a>

</div>
