<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="form-container">
    <div class="authorization">
        <a href="" class="link"><?= __('Sign In') ?></a>
        <a href="" class="link"> <?= __('Sign Up') ?></a>
    </div>
    <form class="form contact" action="<?php echo $block->getFormAction(); ?>" id="contact-form" method="post" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <fieldset class="fieldset row">
                <div class="fields col-md-12">
                    <div class="field name required">
                        <div class="control">
                            <input name="name" id="name" placeholder="<?php echo __('Name') ?>" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" />
                        </div>
                    </div>
                    <div class="field email required">
                        <div class="control">
                            <input name="email" id="email" placeholder="<?php echo __('Email') ?>" title="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" />
                        </div>
                    </div>
                </div>
                <br><br><br><br><br><br>
                <div class="fields col-md-12">
                    <div class="field comment required">
                        <div class="control">
                            <textarea name="comment" id="comment" placeholder="<?php echo __('What’s on your mind?') ?>" title="<?php echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form.additional.info'); ?>
                </div>
            </fieldset>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                    <span><?php echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>