<?php
$footer = $this->getConfig('porto_settings/footer');
?>
<div class="footer">
    <?php
    if (!$footer['footer_top']) {
    ?>
        <div class="footer-top container">
            <?php
            echo  $this->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Magento_Catalog::custom/top_footer.phtml')
                ->toHtml();
            ?>
        </div>
    <?php
    }
    if ($footer['footer_middle']) {
    ?>
        <div class="footer-middle">
            <div class="container">
                <?php
                if ($footer['footer_ribbon']) {
                ?>
                    <div class="footer-ribbon">
                        <span><?php echo $footer['footer_ribbon_text'] ?></span>
                    </div>
                <?php
                }
                ?>
                <div class="row">
                    <?php
                    for ($i = 1; $i <= 4; $i++) {
                        $area = 'footer_middle_column_' . $i;
                        $type = $footer[$area];
                        if ($type) {
                            $t = $footer[$area . '_size'];
                            if ($i == 1) {
                                $t = 4;
                            } elseif ($i == 2) {
                                $t = 8;
                            }
                            echo '<div class="col-lg-' . $t . '" >';
                        }
                        if ($type == 'custom' && $footer[$area . '_custom']) {
                            $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                            if ($block) {
                                $block->setBlockId($footer[$area . '_custom']);
                            }
                            if ($block) {
                                echo $block->toHtml();
                            }
                        }
                        if ($type == 'newsletter') {
                            echo $this->getChildHtml('footer.newsletter');
                        }
                        if ($type) {
                            echo '</div>';
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php
    }
    if ($footer['footer_middle_2']) {
    ?>
        <div class="footer-middle footer-middle-2">
            <div class="container">
                <div class="row">
                    <?php
                    for ($i = 1; $i <= 4; $i++) {
                        $area = 'footer_middle_2_column_' . $i;
                        $type = $footer[$area];
                        if ($type) {
                            echo '<div class="col-lg-' . $footer[$area . '_size'] . '">';
                        }
                        if ($type == 'custom' && $footer[$area . '_custom']) {
                            $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                            if ($block) {
                                $block->setBlockId($footer[$area . '_custom']);
                            }
                            if ($block) {
                                echo $block->toHtml();
                            }
                        }
                        if ($type == 'newsletter') {
                            echo $this->getChildHtml('footer.newsletter');
                        }
                        if ($type) {
                            echo '</div>';
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    <?php
    }
    if ($footer['footer_bottom']) {
    ?>
        <div class="footer-bottom">
            <div class="container" style="text-align:center">
                <?php
                if ($footer['footer_logo_src']) {

                    $url = $this->getFooterLogoSrc();
                ?>
                    <?php if ($this->isHomePage()) : ?>
                        <strong class="logo">
                        <?php else : ?>
                            <a class="logo" href="<?php echo $this->getUrl(''); ?>" title="">
                            <?php endif; ?>
                            <img src="<?php echo $url ?>" alt="" />
                            <?php if ($this->isHomePage()) : ?>
                        </strong>
                    <?php else : ?>
                        </a>
                    <?php endif ?>
                <?php
                } ?>

                <address style="display: contents;">
                    <?php echo $footer['footer_bottom_copyrights'] ?>
                </address>
            </div>
        </div>
    <?php
    }
    ?>
</div>
<a href="javascript:void(0)" id="totop"><em class="porto-icon-up-open"></em></a>
<script type="text/javascript">
    require([
        'jquery',
    ], function($) {
        var x = 0;
        var carouselInterval = setInterval(function() {
            if (++x === 3) {
                $('.owl-carousel').trigger('refresh.owl.carousel');
            }
        }, 300);

        var owl = $('.filterproducts.owl-carousel');
        // owl.owlCarousel();
        // Listen to owl events:
        owl.on('changed.owl.carousel', function(event) {
            var maxHeight = -1;
            $(this).find('.owl-item.active').each(function() {
                if ($(this).height() > maxHeight) {
                    maxHeight = $(this).height();
                }
            });
            var stageOuter = $(this).find('.owl-stage-outer').height();
            // if (stageOuter > maxHeight) {
            //     var height = (stageOuter - maxHeight) + 120;
            // } else {
            //     var height = (stageOuter - maxHeight) + 200;
            // }
            var height = 50 * maxHeight;
            $(this).find('.owl-dots').css('margin-top', height / 100);
            $('.bestsellers-category').find('.owl-dots').css('margin-top', (65 * maxHeight) / 100);

        });

   $('#libra_sub img').hover(function() {

            var hoverSrc = $(this).attr('hover-src');

            var mainSrc = $(this).attr('src');

            $(this).attr('src', hoverSrc);

            $(this).attr('hover-src', mainSrc);

        }, function() {

            var hoverSrc = $(this).attr('hover-src');

            var mainSrc = $(this).attr('src');

            $(this).attr('src', hoverSrc);

            $(this).attr('hover-src', mainSrc);

        });
	
    });
</script>
