<?php
/**
 * Bss Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   Bss
 * @package    Bss_ProductsWidgetSlider
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 Bss Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Magento\Framework\App\Action\Action;



/**
 * Product list template
 *
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\BestSeller
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\MostView
 * @var $block \Bss\ProductsWidgetSlider\Block\Product\OnSale
 */
?>
<?php // @codingStandardsIgnoreFile ?>
<?php
$enable = $block->getEnableConfig();
if(!$enable) {}
else {
    $_productCollection = $block->createCollection();
    $showSlider = $block->getShowSlider();
    $color = $block->getDotsColor();
    $key = $block->genKey();
    if ($showSlider) {
        $countOnPage = 0;
        $productPerSlide = $block->getProductsPerSlide();
        $showNavigation = $block->getShowSlideNavigation();
        $showArrows = $block->getShowArrows();
        $autoPlayEvery = $block->getAutoPlaySlideEvery();
    }?>
    <?php if (!$_productCollection->count()): ?>

    <?php else: ?>
        <?php
        $title = $block->getWidgetName();
            if(!empty($title)){
            ?>
            <h1 class="background"><span><?php echo $block->escapeHtml(__($title)) ?></span></h1>
        <?php } ?>
        <!--    -->
        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showPrice = $block->getShowPrice();
        $showWishlist = $block->getShowWishList();
        $showCompare = $block->getShowCompare();
        $showCart = $block->getShowCart();
        $checker = $block->getShowCart();
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="block widget block-viewed-products">
            <div class="block-content">
                <div class="products wrapper <?= $block->escapeQuote($viewMode) ?> products-<?= $block->escapeQuote($viewMode) ?>">
                    <?php $iterator = 1;?>
                    <ol class="products list items product-items bss-slick-slider<?= $block->escapeQuote($key) ?>">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */?>
                        <?php foreach ($_productCollection as $_product): ?>
                            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                if($showSlider){
                                    $countOnPage++;
                                }
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml()?>
                                </a>
                            </div>
                            <?= ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php
}
?>
