<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();         
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeManager->getStore()->getStoreId() 
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
?>



        <div id="post" class="row pt-2">
            
            <div class="col-xl-4 col-lg-4 col-md-12 post_image">
                <!-- Shto src e imazhit -->
                <div class="image_part">
                    <?php if($post_image = $_post->getFeaturedImage()): ?>
                        <img class="img-fluid" src="<?php echo $post_image; ?>" alt=""/>
                    <?php endif; ?>
                </div>
            
            </div>

            <div class="col-xl-8 col-lg-8 col-md-12 post_content py-3 px-5">
                <!-- Shto titullin -->
                <div id="title" class="col-xl-12">
                    <h1>
                        <a class="post-item-link"
                           href="<?php echo $_postUrl ?>">
                             <?php echo $_postName; ?>
                       </a>
                    </h1>
                </div>
                <div id="content" class="col-xl-12">
                    <p>
            <?php 

                    $string111 = $block->getShorContent();
                    $this_string = strip_tags($string111);

                 ?>
                 <?php $nr_of_charc = strlen($this_string); ?>
                 <?php if ($nr_of_charc > 540): ?>
                     <?php echo substr($this_string, 0, 540).'...' ?>
                 <?php else: ?>
                    <?php echo $this_string; ?>
                 <?php endif ?>
                    </p>
                </div>
                      <a class="post-read-more btn shiko-me-shume" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                        <?php echo __('View more'); ?>
                      </a>

            </div>

        </div>
  
