<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();         
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 $storeManager->getStore()->getStoreId() 
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="post-banner no-banner"></div>
    <div class="post-date">
        <span class="day"><?php echo date("j", strtotime($_postDate)); ?></span>
        <span class="month"><?php echo date("M", strtotime($_postDate)); ?></span>
    </div>
    <div class="post-header">
         <div class="imgage_part">
                    <?php if($post_image = $_post->getFeaturedImage()): ?>
                        <img src="<?php echo $post_image; ?>" alt=""/>
                    <?php endif; ?>
                    </div>
                    <div class="post-content">
        <div class="post-title-holder">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                    <?php echo $_postName; ?>
                </a>
            </h2>
        </div>
        
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?php 

                    $string111 = $block->getShorContent();
                    $this_string = strip_tags($string111);

                 ?>
                 <?php $nr_of_charc = strlen($this_string); ?>
                 <?php if ($nr_of_charc > 540): ?>
                     <?php echo substr($this_string, 0, 540).'...' ?>
                 <?php else: ?>
                    <?php echo $this_string; ?>
                 <?php endif ?>
                <?php //echo $block->getShorContent() ?>
            </div>
            <?php if($storeManager->getStore()->getStoreId() ==2):?>
            <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
               <?php echo __('Shiko më shumë'); ?>
            </a>
        <?php else:?>
            <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
               <?php echo __('View more'); ?>
            </a>
        <?php endif;?>
        </div>
    </div>
    </div>

    
    <div class="post-footer">
        <?php echo $this->getInfoHtml() ?>
    </div>
</li>