<div class="banner collection">
  <p>
    Our spring collection is in the air
    <span>30%</span>
  </p>

  <button type="button" name="button"> <?= __('Buy Now') ?> </button>
</div>


<!---

{{block class="Smartwave\Filterproducts\Block\Home\BestsellersList" name="hot_product" category_id="13" product_count="8" hide-addtolinks="1" aspect_ratio="0" image_width="180" image_height="180" template="owl_list.phtml"}}

--->
