<div class="banner sales">
  <span class="img">
      <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/lines.png'; ?>" class="lines" alt="">
      <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/autoporlant.png'; ?>" class="altoporlant" alt="">
  </span>

<div class="vectors">

  <img class="bf-hc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/half-of-the-circle.png'; ?>" alt="">
  <img class="bf-wc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/white-circle.png'; ?>" alt="">


  <img class="af-wc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/white-circle.png'; ?>" alt="">
  <img class="af-hc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/half-of-the-circle.png'; ?>" alt="">
  <img class="af-dl" src="<?= $this->getUrl('pub/media') . 'wysiwyg/diagonal-line.png'; ?>" alt="">

</div>


  <p>
    Libra per femije <span>50%</span> ulje
  </p>
<div class="vectors">
  <img class="dl" src="<?= $this->getUrl('pub/media') . 'wysiwyg/diagonal-line.png'; ?>" alt="">
  <img class="hc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/half-of-the-circle.png'; ?>" alt="">
  <img class="wc" src="<?= $this->getUrl('pub/media') . 'wysiwyg/white-circle.png'; ?>" alt="">

</div>
  <button type="button" name="button">Bli Tani</button>

</div>
