<div class="top-footer banner row">
  <span class="col-lg-6">
    <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/b-logo.png'; ?>"  alt="">
  </span>
  <span class="col-lg-6">
    <p> <?= __("Comming soon") ?>  </p>
    <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/google-play.png'; ?>"  alt="">
    <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/app-store.png'; ?>"  alt="">
  </span>
</div>
