<div class="top-footer container banner row">
  <span class="col-lg-6">
    <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/b-logo.png'; ?>"  alt="">
  </span>
  <span class="col-lg-6"     style="justify-content: flex-end;">
    <p> <?= __("Comming soon") ?>  </p>
    <img style="padding:0 20px;" src="<?= $this->getUrl('pub/media') . 'wysiwyg/google-play.png'; ?>"  alt="">
    <img src="<?= $this->getUrl('pub/media') . 'wysiwyg/app-store.png'; ?>"  alt="">
  </span>
</div>
