<?php

$_product = $block->getProduct(); 

$age 		= null;
$attr 		= null;
$isbn       = null;
$pages		= null;
$dimensions = null;

$age 		= $_product->getAge();
$attr 		= $_product->getCustomAttribute('page');
$isbn 		= $_product->getIsbn();
$dimensions = $_product->getDimensions();

if (!is_null($attr)) {
	$pages =  $attr->getValue();
}

?>


<div class="custom_attr container">
	<div class="row">
		<?php if($isbn){ ?>
			<span class="col-6" ><strong>Isbn: </strong><?= $isbn ?> </span>
		<?php } if($age){ ?>
			<span class="col-6" ><strong>Mosha: </strong><?= $age ?> </span>
		<?php } ?>
	</div>
	<br>
	<div class="row">
		<?php if($dimensions){?>
			<span class="col-6" ><strong>Permasat: </strong><?= $dimensions ?> </span>
		<?php } if($pages){ ?>
			<span class="col-6" ><strong>Faqe: </strong><?= $pages ?> </span>
		<?php } ?>
	</div>

</div>
<br>

<script type="text/javascript">
      require([
            'jquery',
        ], function ($) {
            $('.reviews-actions a').click(function(){
            	$('.product.info.detailed').show();
            })
        });
</script>