<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>
<div id="back-to-book" style="display: none;">
    <img src="<?= $mainImageData ?>" alt="">
    <h2><?= $block->getProduct()->getName() ?></h2>
    <p><?= __('Return back to book') ?></p>
</div>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img alt="main product photo" class="gallery-placeholder__image" src="<?= /* @noEscape */ $mainImageData ?>" />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).ready(function() {
            let timer = setInterval(function() {
                if ($('.fotorama__nav-wrap').length != 0) {
                    var text = "<?= __("Look Inside") ?>";
                    $('.fotorama__nav-wrap').prepend("<p class='fotorama-text-intro'>" + text + "</p>");
                    clearInterval(timer)
                }
            }, 500);


        });
        $(document).ready(function() {
            var width = $(window).width();
            if (width > 767) {
                let timer = setInterval(function() {
                    var item = $(document).find('.fotorama-item');
                    if ($(item).length != 0) {
                        item.on('fotorama:fullscreenenter', function() {
                            $('#back-to-book').show();
                        });
                        item.on('fotorama:fullscreenexit', function() {
                            $('#back-to-book').hide();
                        });
                        $('#back-to-book p').click(function() {
                            $('.fotorama').data('fotorama').cancelFullScreen();
                        })
                        clearInterval(timer)
                    }
                }, 500);
            }
        });

    });
</script>
