<?php
$product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$categoryIds = $product->getCategoryIds();
$key = array_rand($categoryIds);
$value = $categoryIds[$key];
$image = 'category_page_grid';
$_lazyload = false;
$aspect_ratio = true;
$image_width = 400;
$image_height = 400;

$relatedProducts = $product->getRelatedProductCollection()->addAttributeToSelect('*');
if (count($relatedProducts) > 0) {
	$relatedProductCollection = $relatedProducts;
} else {



	$relatedProductsBlock =  $block->getLayout()
		->createBlock('Atniqii\Aeditions\Block\RelatedProducts');
	$category = $relatedProductsBlock->getCategory($value);

	$relatedProductCollection = $relatedProductsBlock->getProductCollection();
	$relatedProductCollection->addStoreFilter();
	$relatedProductCollection->addAttributeToSelect('*')
		->addAttributeToFilter('sku', ['neq' => $product->getSku()])
		->addAttributeToFilter(
			'status',
			array('eq' => \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED)
		);
	$relatedProductCollection->addCategoryFilter($category);
	$relatedProductCollection->setPageSize(10);
}

?>
<?php
$viewMode = 'grid';
$image = 'category_page_grid';
$hover_image = 'category_page_grid-hover';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<div class="main_addtion_product_bg">
	<div class="col-sm-12">
		<h2 class="filterproduct-title">
			<span class="content">
				<strong>
					<?= __('Related Products') ?>
				</strong>
			</span>
		</h2>
		<div id="r_products" class="owl-top-narrow">
			<div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
				<?php $iterator = 1; ?>

			</div>
			<div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				<div class="filterproducts products list items product-items owl-carousel">
					<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
					<?php foreach ($relatedProductCollection as $_product) : ?>
						<?php echo ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
						<div class="product-item-info" data-container="product-grid">
							<?php // Product Image
							?>
							<div class="product photo product-item-photo">
								<a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1">
									<?php
									if ($aspect_ratio)
										$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
									else
										$productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
									$productImageUrl = $productImage->getUrl();
									?>
									<img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" />
								</a>
							</div>
							<div class="product details product-item-details">
								<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
										<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>

								<?php if ($showDescription) : ?>
									<div class="product description product-item-description">
										<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="action more"><?php echo __('Learn More') ?></a>
									</div>
								<?php endif; ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>


							</div>
						</div>
						<?php echo ($iterator == count($relatedProductCollection) + 1) ? '</div>' : '' ?>
					<?php endforeach; ?>
				</div>
			</div>

			<script type="text/javascript">
				require([
					'jquery',
					'owl.carousel/owl.carousel.min'
				], function($) {

					$("#r_products .owl-carousel").owlCarousel({
						autoplay: true,
						autoplayTimeout: 5000,
						autoplayHoverPause: true,
						loop: true,
						dots: false,
						navRewind: true,
						//margin: 10,
						nav: true,
						navText: ["<em class='porto-icon-left-open-huge'></em>", "<em class='porto-icon-right-open-huge'></em>"],
						responsive: {
							0: {
								items: 1
							},
							600: {
								items: 2
							},
							768: {
								items: 3
							},
							992: {
								items: 4
							},
							1200: {
								items: 4
							}
						}
					});

						var imgHeight = $('.catalog-product-view .main_addtion_product_bg .owl-item').first().height();
							if (imgHeight > 500) {
								$('.catalog-product-view .main_addtion_product_bg .owl-item img').css('height', '200px');
								$('.catalog-product-view .main_addtion_product_bg .owl-item img').css('width', 'auto');
								$('.catalog-product-view .main_addtion_product_bg').css('margin-bottom', '30px');
								}
					var height = $('.catalog-product-view .main_addtion_product_bg .owl-item').first().height() + 20;
					$('.main_addtion_product_bg .owl-top-narrow .owl-theme .owl-controls .owl-nav').css('margin-top', -(60 / 100) * height);
					$('.catalog-product-view .main_addtion_product_bg').css("height", height + "px");
					$('.category-harta .main_addtion_product_bg .owl-top-narrow .owl-theme .owl-controls .owl-nav').css('margin-top', -(60 / 100) * (height + 20));
				});
			</script>
		</div>
