<?php

$_product = $block->getProduct();
$productImageUrl = $block->getUrl('pub/media/catalog') . 'product' . $_product->getImage();
?>
<div class="wdm-social-icons" data-role="wdm-social-icons">
   <div class="view_share_bg">
      <p><?= __('Share') ?></p>
      <ul>
         <li>
            <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl()); ?>&t=<?php echo urlencode($_product->getName()) ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on 	  FaceBook">
               <img src="<?= $block->getUrl('pub/media') ?>fb.png" alt="">
            </a>
         </li>
         <li>
            <a href="https://www.linkedin.com/sharing/share-offsite/?url=<?php echo $_product->getProductUrl(); ?>" onclick='javascript:window.open(this.href,""," width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false'>
               <img src="<?= $block->getUrl('pub/media') ?>ln.png" alt="">
            </a>
         </li>
         <li>
            <a href="https://www.pinterest.com/pin/create/button/?url=<?php echo urlencode($_product->getProductUrl()); ?>&media=<?php echo urlencode($productImageUrl) ?> &description=<?php echo urlencode($_product->getName()) ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false'>
               <img src="<?= $block->getUrl('pub/media') ?>pt.png" alt="">
            </a>
         </li>
      </ul>
   </div>
</div>