<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
?>
<style media="screen">
.page-header.type19 .panel.header .switcher-trigger:after{
  display: none;
}
</style>
<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>
                    <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($block->escapeHtml($block->getCurrentStoreCode())).'.png'; ?>" />
                <?php endif; ?>
            </strong>
        </div>
        <?php foreach ($block->getStores() as $_lang): ?>
            <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>

              <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
                  <strong class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">

                    <a href="#" data-post='<?php echo $this->getTargetStorePostData($_lang); ?>'>
                        <?php if($_helper->getConfig('porto_settings/header/language_flag')): ?>
                            <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/smartwave/porto/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" />
                        <?php endif; ?>
                    </a>
                  </strong>
              </div>

            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
